### ISSUE TITLE
Type in tagging script

### ISSUE THREAD

**Issue by borourke** [awslabs/lambda-streams-to-firehose#1]
Currently the "tagStream.sh" script has the line:

```
aws kinesis add-tags-to-stream --stream-name $1 --Tags ForwardToFirehoseStream=$2 --region $3
```

But according to the Kinesis docs, --Tags should actually be lower case: http://docs.aws.amazon.com/cli/latest/reference/kinesis/add-tags-to-stream.html.

It will give you this error unless you change to lower case:
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --tags is required
```

Simple bug fix, and easy enough to work around, just wanted to put it on your radar.

Btw, thanks for this repo, this fits perfectly for what my company is trying to do with streams.

**Comment by IanMeyers** [comment]
Dunno how that slipped through. Thanks for flagging. Have fixed now.
