### ISSUE TITLE
Not sure this project works

### ISSUE THREAD

**Issue by benburkhart1** [awslabs/lambda-streams-to-firehose#11]
I've been trying to use this project without success.

I have a DynamoDB table, that matches my table name in Redshift.

I've setup the DynamoDB table to stream to the lambda function, which I've uploaded this project's zip file, with the default stream stuff disabled.

I've setup a Kinesis Firehose connection to Redshift.

The issue is that the redshift load fails because the data it is trying to load is not in any format redshift expects. You reference line numbers all over the place in the documentation, but they don't match up because they were not updated with the code. I'm just not sure this code has ever been tested with dynamodb streams or works.

The attached file is the file it's attempting to load via the COPY command in redshift. 
[example.txt](https://github.com/awslabs/lambda-streams-to-firehose/files/377203/example.txt)

**Comment by aflatten** [comment]
In case it helps, I can confirm it definitely works.  We use it to replicate several DynamoDB tables to Redshift -- it's pretty amazing.  We're getting near real-time replication at scale.

One thing you may want to look at is configuring your Firehose delivery stream with the appropriate COPY options.  In particular, you'll probably need to point it to a [JSON mapping file](http://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-column-mapping.html#copy-column-mapping-jsonpaths) if you haven't already.  This tells Redshift how to convert the raw data from DynamoDB into a format for your Redshift table...

For example, if your Redshift table looks something like this:
```
CREATE TABLE IF NOT EXISTS "MyTable"
(
  referer varchar,
  request_timestamp varchar ,
  old_hash varchar,
  write_timestamp varchar,
  SequenceNumber NUMERIC(38, 0)
);
```

You would want a mapping file that looks like this:
```
{
    "jsonpaths": [
        "$['NewImage']['referer']['S']",
        "$['NewImage']['request_timestamp']['S']",
        "$['NewImage']['old_hash']['S']",
        "$['NewImage']['write_timestamp']['S']",
        "$['SequenceNumber']"
    ]
}
```
Then, upload that to S3 and configure your Firehose stream with this value for the _Redshift Copy Options_:  `json 's3://your-bucket-goes-here/path-to-your-json-mapping-file'`

**Comment by benburkhart1** [comment]
@aflatten Thank you so much for responding. I'll try and submit a PR with some changes to documentation suggesting this step. Much appreciated.
