### ISSUE TITLE
Problems with international characters

### ISSUE THREAD

**Issue by evenv** [awslabs/lambda-streams-to-firehose#12]
Hi,

When dumping a message with international characters to an S3 Firehose, it seems the international characters get messed up in the resulting S3 file. When tailing the Kinesis Stream using aws cli and base64 decoding the result to UTF-8, the result is correct, But when opening the resulting S3 file, the characters get replaced with something I haven't been able to decode.
Examples:
"Østover" becomes "C[CAN]stover" (CAN being the ASCII Cancel symbol)
"ELÅ2" becomes "ELC[ENQ]2" (ENQ being the ASCII Enquiry symbol)

Any thoughts on what could be wrong?

**Comment by vb3** [comment]
https://github.com/awslabs/lambda-streams-to-firehose/blob/master/index.js#L359 needs to be 'utf8'

**Comment by evenv** [comment]
Thanks! I've made a fork moving the encoding to a constant at the top and changing it to utf-8, also removing the JSON.stringify from addNewlineTransformer as per https://github.com/awslabs/lambda-streams-to-firehose/issues/5. If you want I could submit it as a pull request? (From my point of view it should be the default behavior, but it's up to you).

**Comment by IanMeyers** [comment]
I've pushed version 1.3.3. which should address this issue similarly to your fork, but there were a few other places that it needed to be changed. Can you retest with 1.3.3 version?

**Comment by IanMeyers** [comment]
Closing this now - please re-open if you still have issues.

**Comment by evenv** [comment]
Sorry for the delayed feedback. We've retested and looks like it's working fine now. Thanks for the fix!
