### ISSUE TITLE
How to change delivery stream for existing input stream (using tags)?

### ISSUE THREAD

**Issue by evenv** [awslabs/lambda-streams-to-firehose#19]
Updating the ForwardToFirehoseStream tag for a Kinesis stream doesn't affect the delivery of the stream - it still delivers to the old firehose. From looking at the .js it seems the deliveryStreamMapping is redefined only at the start of the file before the handler. I guess this is really more of a Lambda question, but anyway: How can I get the Lambda function to pick up the updated delivery stream tag?

**Comment by benoittgt** [comment]
Did you find a solution?

**Comment by IanMeyers** [comment]
Hi - that's not currently supported, and would only take effect when the Lambda container was restarted (probably about every 4 hours). Happy to take a PR that reloads the configuration every N period or something.
