### ISSUE TITLE
deliveryStreamNames longer than 64 characters cause validation error

### ISSUE THREAD

**Issue by BMR59920** [awslabs/lambda-streams-to-firehose#23]
Dynamo DB name as stream name 

2016-11-07T23:58:17.506Z	19be6906-42f0-4508-8e14-3848090361ad
{
    "message": "1 validation error detected: Value 'bobStackLocal-DynamoDBLocalSUPV1-1WR799B0232B3-dataUnit-NC39DWFYPYIQ' at 'deliveryStreamName' failed to satisfy constraint: Member must have length less than or equal to 64"

Related: https://github.com/awslabs/dynamodb-continuous-backup/issues/5

**Comment by IanMeyers** [comment]
Fixed just now

**Comment by BMR59920** [comment]
This appears to have been fixed. Thank you!

**Comment by BMR59920** [comment]
That particular error has been addressed. However LambdaStreamToFirehose showing that records are being forwarded to delivery stream that has the full table name...

2016-11-11T18:14:03.082Z	2be9bf09-e709-4662-b746-2ab509fbcd35	Event forwarding complete. Forwarded 1 batches comprising 1 records to Firehose bobStackDev-DynamoDBDevPDV1-JSQ9YN1TA6XL-coreCollection-10JU047A8CKTF

But the name does not match what is provisioned as a firehose stream truncated name.

bobStackDev-DynamoDBDevPDV1-JSQ9YN1TA6XL-coreCollection-10JU047A	 bob-dynamo-backups	GZIP	No Encryption	ACTIVE

**Comment by BMR59920** [comment]
This issue is resolved. Thank you!
