### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by benoittgt** [awslabs/lambda-streams-to-firehose#27]
Hello

I'm using this lambdas in production and with my team we love to use code who is tested. I wonder if testing the behavior of his lambda is something other people want? 

If yes what will be your requirements? Local testing (aka mocking external call with proxyquire for example)?

Thanks

**Comment by IanMeyers** [comment]
Hi - I've added one of the mocha tests that I created for the routing capability. That's a style I'd like to stick with, but very open to additions that build upon this with other types of mocks. Thanks in advance!

**Comment by benoittgt** [comment]
Thanks a lot @IanMeyers. Still fast ! Will take a look.

**Comment by benoittgt** [comment]
I tried to add a test for handler function but before going further I would like to know how you would like to test it. I'm using proxyquire but it requires a lot of code to mock aws-sdk. Maybe we should mock http calls or something else ?

https://github.com/benoittgt/lambda-streams-to-firehose/commit/6aa36ac85c73ee2e84273816bbddf233ac416310

Feel free to comment on the commit if you think I should spend time on this.

**Comment by benoittgt** [comment]
@IanMeyers Feel free to make any comments. I'm still interested to test the lambda.

**Comment by IanMeyers** [comment]
What we've done elsewhere was to export all the internal modules, which in some cases has required refactoring the handler() method, and then add mocha tests (for node.js of course). This would be the model I would propose here, but can be difficult where AWS services are hard dependencies.

**Comment by benoittgt** [comment]
> but can be difficult where AWS services are hard dependencies.

Yes I was wondering If you have a pattern you used when hitting AWS services (like webmock, or mocking lib with proxyquire, etc). 

I will try to see what I can extract in the same way you did for the routing.

**Comment by IanMeyers** [comment]
Haven't tried it, but https://github.com/atlassian/localstack might be an option...

**Comment by benoittgt** [comment]
Stale issue. Closing for now.
