### ISSUE TITLE
exports.onCompletion is not a function

### ISSUE THREAD

**Issue by tnixon** [awslabs/lambda-streams-to-firehose#36]
index.js lines 276, 326 refer to 'exports.onCompletion', but the onCompletion method is never added to exports.

**Comment by benoittgt** [comment]
Hello @tnixon 

You should check the last update : https://github.com/awslabs/lambda-streams-to-firehose/commit/06a48bfd8b505c3029b467093ea6590519b6f725

😉

**Comment by tnixon** [comment]
Great!
