### ISSUE TITLE
require aws-kpl-deagg

### ISSUE THREAD

**Issue by jeremyhartley** [awslabs/lambda-streams-to-firehose#4]
After running ./build.sh, and uploading the resulting dist .zip file to lambda, I was getting the following error in my logs when the lambda function was invoked by a kinesis event:

Unable to import module 'index': Error at Function.Module._resolveFilename (module.js:338:15)

Seems like I had to install the deaggregator package first, even after running "npm install" for the first time (which, at present, seems to only include async package).

`npm install aws-kpl-deagg`

Anyway, simple fix. Maybe it helps somebody else :)

**Comment by IanMeyers** [comment]
Fixed!
