### ISSUE TITLE
Question about lambda - error handling

### ISSUE THREAD

**Issue by liat-barel** [awslabs/lambda-streams-to-firehose#44]
Does the lambda has any logic that enables it to read again same messages from the kinesis in next invocation in case of failure?  Are there checkpoints?

**Comment by benalta** [comment]
if a Lambda function fails, AWS Lambda attempts to process the erroring batch of records until the time the data expires which can be between 24 hours to 7 days depends how you defined your kinesis stream

**Comment by liat-barel** [comment]
Got it. Many thanks for the prompt reply.

**Comment by Dhinendran** [comment]
how to use existing dynamo DB to kinesis firehose that stream dynamo DB data to s3

**Comment by IanMeyers** [comment]
@Dhinendran this is documented on https://github.com/awslabs/lambda-streams-to-firehose/issues/58
