### ISSUE TITLE
init does not call callback on subsequent runs

### ISSUE THREAD

**Issue by dandalf** [awslabs/lambda-streams-to-firehose#53]
When init is initially called, it sets up the streams and does a callback to the handler.
When it is called a second time, it sees online === true, so it skips the callback resulting in the lambda to just fail silently.
Pull request incoming.

**Comment by rhamnett** [comment]
I can confirm this is an issue and the above fix provides the remedy. Sooner this gets merged the better. Thanks.

**Comment by dandalf** [comment]
Fix was merged!
