### ISSUE TITLE
Question on how to configure function for DDB Stream delivery to S3

### ISSUE THREAD

**Issue by IanMeyers** [awslabs/lambda-streams-to-firehose#58]
To configure the module to run for DynamoDB Update Streams, simply:

- Create a Firehose Delivery Stream with the same name as the DynamoDB Table in the same Region
- Configure Update Streams on your DynamoDB table, ideally with OLD_AND_NEW_VERSIONS included
- Deploy the LambdaStreamsToFirehose function to AWS Lambda
- Create the Event Source for the Lambda function from the DynamoDB Table Update Stream

**Comment by Dhinendran** [comment]
hi sir,
1.Deploy the LambdaStreamsToFirehose function to AWS Lambda
2.Create the Event Source for the Lambda function from the DynamoDB Table Update Stream
how to configure this steps

**Comment by IanMeyers** [comment]
Perhaps have a review of [this tutorial](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb-example.html) and then let me know if you have other questions?

**Comment by wagneraw** [comment]
You can also take a look at this blog post, which walks you through archiving DDB items to S3 using this library: [https://aws.amazon.com/blogs/database/automatically-archive-items-to-s3-using-dynamodb-time-to-live-with-aws-lambda-and-amazon-kinesis-firehose/](https://aws.amazon.com/blogs/database/automatically-archive-items-to-s3-using-dynamodb-time-to-live-with-aws-lambda-and-amazon-kinesis-firehose/)

**Comment by Dhinendran** [comment]
sir doubt in TTL method 
can't understand this step --1.You’re now ready to package up the Lambda function. Running the included ./build.sh zips up the function and places it in dist/LambdaStreamToFirehose-1.4.5.zip.
2.In lambda, if I upload zip file means error "it's too large to enable inline code editing"

**Comment by wagneraw** [comment]
That blog post shows the steps of creating the DynamoDB Stream and the Lambda Event Source, which is the same even if you're not enabling TTL. The Lambda message about the function being too large of inline code editing is expect. Larger Lambda functions aren't able to be editing using the editor built into the console. Hope that helps!
