### ISSUE TITLE
Code throws exception in line 450

### ISSUE THREAD

**Issue by ibnipun10** [awslabs/lambda-streams-to-firehose#6]
When running the code in lambda, it gives exception in line 450 saying
"Undefined is not a function ", in this line
"if (event.Records[0].eventSource === KINESIS_SERVICE_NAME || event.Records[0].eventSource === DDB_SERVICE_NAME)"

**Comment by IanMeyers** [comment]
Is this consistently reproducible? Have not experienced this myself, and there are guards against this having an issue with undefined values earlier in the code...

**Comment by IanMeyers** [comment]
If you can repro, can you please deploy distribution 1.3.1 and see if the issue persists?

**Comment by ibnipun10** [comment]
I see code changes in the history regarding handling no entries. Let me work with the the new code and let you know
