### ISSUE TITLE
Support for filtering by event types

### ISSUE THREAD

**Issue by athityakumar** [awslabs/lambda-streams-to-firehose#66]
Hey there! 👋 

We're using this repo code as a lambda to write DynamoDB input to Firehose streams output. Now we have come across a "AppendOnly" use-case, wherein we need to write only the INSERT events, and ignore the MODIFY/DELETE events.

We've implemented a change on top of this repo, adding `writableEventTypes` as a comma-separated environment variable to the lambda. Just wanted to check if anyone has a similar use-case, and if we could create a PR for the same to this repo.

Ofcourse, if there's a more compatible way of adding this change, please let me know and I'll then open the PR. Jut wanted to check this is a compatible change with the maintainers of this repo, before going ahead to open a PR! 😄 

And awesome work with this repo! TIA! 🎉

**Comment by athityakumar** [comment]
PS: #59 is not exactly the same, but a similar feature request

**Comment by athityakumar** [comment]
Ping @IanMeyers ^

**Comment by IanMeyers** [comment]
happy to have a PR that does this, for sure.

**Comment by athityakumar** [comment]
@IanMeyers - Awesome, I've opened #67 for the same. Can you please review? 😄

**Comment by IanMeyers** [comment]
Merged
