### ISSUE TITLE
`finish` arguments constructed erroneously with `undefined` value

### ISSUE THREAD

**Issue by jamesthompson** [awslabs/lambda-streams-to-firehose#9]
In the following code snippet:
https://github.com/awslabs/lambda-streams-to-firehose/blob/master/index.js#L472-L479

A map key is being deleted:
https://github.com/awslabs/lambda-streams-to-firehose/blob/master/index.js#L475

Then the key fetch will result in undefined?
https://github.com/awslabs/lambda-streams-to-firehose/blob/master/index.js#L477

Should the underlying value should be assigned to a variable for comparison prior to `delete` being called on the key?

**Comment by IanMeyers** [comment]
Fixed in PR 10
